name: Pipelines With .NET 10 Demo

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
        id: color-selector

      - name: Print build info
        run: dotnet run PrintBuildInfo.cs
        working-directory: ${{ github.workspace }}/.github/workflows/scripts

      - name: Fetch todo
        id: fetch-todo
        run: |
          cat <<EOL > FetchTodo.cs
          using System.Net.Http.Json;

          HttpClient apiClient = new() { BaseAddress = new("https://jsonplaceholder.typicode.com/") };
          Todo? todo = await apiClient.GetFromJsonAsync<Todo>("todos/1");
          SetGitHubOutput("TODO_TITLE", todo?.Title);

          static void SetGitHubOutput(string key, string? value)
          {
              string outputFilePath = Environment.GetEnvironmentVariable("GITHUB_OUTPUT")!;
              File.AppendAllText(outputFilePath, $"{key}={value}\n");
          }

          record Todo(int UserId, int Id, string Title, bool Completed);
          EOL
          dotnet run FetchTodo.cs

      - name: Print todo title
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
          TODO_TITLE: ${{ steps.fetch-todo.outputs.TODO_TITLE }}
        run: |
          echo "$SELECTED_COLOR"
          echo "$TODO_TITLE"
      
