name: Pipelines With .NET 10 Demo

on:
  workflow_dispatch:
  push:
    branches: 
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - run: dotnet run PrintBuildInfo.cs
        name: Print build info
        working-directory: ${{ github.workspace }}/.github/workflows/scripts

      - run: |
          cat <<EOL > FetchTodo.cs
          using System.Net.Http.Json;
          HttpClient client = new();
          Todo? todo = await client.GetFromJsonAsync<Todo>("https://jsonplaceholder.typicode.com/todos/1");
          Console.WriteLine(todo);
          record Todo(int UserId, int Id, string Title, bool Completed);
          EOL
          dotnet run FetchTodo.cs
        name: Fetch TODO
      
